research_task:
  description: >
    Conduct foundational research on {topic} including:
    1. Core definitions and background
    2. Current relevance (as of {current_year})
    3. Recent developments or applications
    4. Key stakeholders or debates
  expected_output: >
    A structured document with 5-7 bullet-pointed insights on {topic}, citing credible sources.
  agent: researcher
  context: []

reporting_task:
  description: >
    Using the output from the research_task, develop an expanded, structured report covering:
    1. Executive summary
    2. Thematic sections with explanatory detail
    3. Implications and recommendations
  expected_output: >
    A professional markdown report with headings, citations, and a conclusion that builds on the research.
  context:
    - research_task
  agent: reporting_analyst

content_accuracy_check_task:
  description: >
    Verify all factual claims in the educational materials about {topic}.
    Ensure academic rigor by cross-referencing with scholarly sources.
  expected_output: >
    Annotated content with citations, a summary of corrections, and a confidence score per section.
  agent: content_reviewer
  context: []

# src/guide_creator_flow/crews/content_crew/config/tasks.yaml

write_section_task:
  description: >
    Write a comprehensive section on the topic: "{section_title}"

    Section description: {section_description}
    Target audience: {audience_level} level learners

    Your content should:
    1. Begin with a brief introduction to the section topic
    2. Explain all key concepts clearly with examples
    3. Include practical applications or exercises where appropriate
    4. End with a summary of key points
    5. Be approximately 500-800 words in length

    Format your content in Markdown with appropriate headings, lists, and emphasis.

    Previously written sections:
    {previous_sections}

    Make sure your content maintains consistency with previously written sections
    and builds upon concepts that have already been explained.
  expected_output: >
    A well-structured, comprehensive section in Markdown format that thoroughly
    explains the topic and is appropriate for the target audience.
  agent: content_writer

curriculum_task:
  description: >
    Using the report from the reporting task, develop a structured curriculum outline for {topic}.
    Include learning objectives, key concepts, and recommended activities.
  expected_output: >
    A complete curriculum outline in markdown format with clear sections, learning goals, and content structure.
  agent: curriculum_developer
  context:
    - reporting_task

lesson_enhance_task:
  description: >
    Review and enhance the curriculum content for {topic}, ensuring it is engaging,
    accurate, and follows best practices in educational content design.
  expected_output: >
    An enhanced version of the curriculum with improved clarity, engagement strategies, and educational value.
  agent: content_reviewer
  context:
    - curriculum_task