# 🧠 assignment_ai_review_flow.py
# Analyze how AI could shortcut the assignment and suggest redesign strategies

import os
from pathlib import Path
import fitz  # PyMuPDF for PDF parsing
from crewai import Crew, Agent, Task
from drmz.crews.config_loader import load_agents, load_tasks
from drmz.utils.logger import get_logger
from drmz.utils.file_utils import ensure_dir
from drmz.utils.path_utils import OUTPUT_DIR

# === Setup ===
log = get_logger("AssignmentAIReview")
agents_config = load_agents()
tasks_config = load_tasks()

TASK_NAME = "ai_review_assignment_task"
OUTPUT_FOLDER = OUTPUT_DIR / "assignments" / "ai_review"
ensure_dir(OUTPUT_FOLDER)

def extract_text(file_path: Path) -> str:
    """Extract text from .pdf or .txt file."""
    if file_path.suffix.lower() == ".txt":
        return file_path.read_text(encoding="utf-8")
    elif file_path.suffix.lower() == ".pdf":
        resolved = str(file_path.resolve())
        log.info(f"🧪 Opening file: {resolved}")
        doc = fitz.open(resolved)
        return "\n".join(page.get_text() for page in doc)
    else:
        raise ValueError(f"Unsupported file type: {file_path.suffix}")

def run_assignment_review(file_path: Path) -> str:
    log.info(f"🚀 Running AI Review on: {file_path.name}")
    content = extract_text(file_path)

    task_config = tasks_config[TASK_NAME]
    agent_key = task_config["agent"]
    agent_data = agents_config[agent_key]

    # === Load Morpheus (main agent) ===
    morpheus = Agent(
        role=agent_data["role"],
        goal=agent_data["goal"],
        backstory=agent_data["backstory"],
        llm=agent_data["llm"],
        allow_delegation=task_config.get("config", {}).get("allow_delegation", False),
    )

    # === Optional support agents ===
    support_agent_keys = ["curriculum_developer", "ai_integrationist", "faculty_coach"]
    support_agents = []
    for key in support_agent_keys:
        if key in agents_config:
            a = agents_config[key]
            support_agents.append(
                Agent(
                    role=a["role"],
                    goal=a["goal"],
                    backstory=a["backstory"],
                    llm=a["llm"],
                    allow_delegation=False,
                )
            )

    # === Construct the full task description ===
    full_description = (
        task_config["description"]
        + "\n\n--- ASSIGNMENT PROMPT START ---\n"
        + content
        + "\n--- ASSIGNMENT PROMPT END ---"
    )

    task = Task(
        description=full_description,
        expected_output=task_config["expected_output"],
        agent=morpheus,
    )

    # === Build and run the crew ===
    crew = Crew(
        agents=[morpheus] + support_agents,
        tasks=[task],
        verbose=True
    )

    try:
        result = crew.kickoff()
        if not result or not str(result).strip():
            result = "⚠️ No output was generated by the AI Review task."
        else:
            log.info("✅ Crew returned a valid result.")
    except Exception as e:
        log.exception("❌ Crew execution failed:")
        result = f"❌ Error during AI Review: {str(e)}"

    # === Write output file ===
    output_path = OUTPUT_FOLDER / f"{file_path.stem}_ai_review.md"
    try:
        output_path.write_text(result, encoding="utf-8")
        log.info(f"💾 Saved output to: {output_path}")
    except Exception as e:
        log.exception("❌ Failed to save output:")
    return result

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", type=str, help="Path to .pdf or .txt assignment")
    args = parser.parse_args()

    if args.file:
        file_path = Path(args.file)
        result = run_assignment_review(file_path)
        print("\n🧠 FINAL OUTPUT:\n")
        print(result)

if __name__ == "__main__":
    main()
